### ISSUE TITLE
$entry->getMedia ?

### ISSUE THREAD

**Issue by tiagosimoesdev** [Gaspertrix/laravel-backpack-dropzone-field#1]
Hi, thanks for the package . 
I followed your steps but when editing an entry I get 

" Call to undefined method App\Models\Venda::getMedia() "

**Comment by egerb** [comment]
> Hi, thanks for the package .
> I followed your steps but when editing an entry I get
> 
> " Call to undefined method App\Models\Venda::getMedia() "

Install Spatie Laravel Medialibrary

**Comment by egerb** [comment]
Also put autoDiscover option before $(document).ready.

**Comment by tiagosimoesdev** [comment]
Yeah.. forgot to install spattie media-library .. thank you . Now got some JS errors : 

`Uncaught Error: No URL provided.`
And
`Uncaught Error: Dropzone already attached.`


Adding `Dropzone.autoDiscover = false;` to `true` won't fix .

**Comment by tiagosimoesdev** [comment]
Sorry missread your comment before . Adding  `autoDiscover ` before $(document).ready works !
