### ISSUE TITLE
Getting Error trying to use package

### ISSUE THREAD

**Issue by hypnom** [Gaspertrix/laravel-backpack-dropzone-field#3]
Hello, i get error trying to edit entry "Argument 1 passed to Spatie\MediaLibrary\MediaRepository::getCollection() must be an instance of Spatie\MediaLibrary\HasMedia\HasMedia, instance of App\Models\Testgal given" what im doing wrong?

Ive added 
"use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;"

and "use HasMediaTrait;" in model before CrudTrait

p.s. not sure about editing medialibrary default config (may be it is a problem?)

**Comment by jishnu2292** [comment]
add "**implements HasMedia**" in your model.
eg: class _ClassName_ extends Model **implements HasMedia**
{
......
}
