### ISSUE TITLE
How to view uploaded images in backpack crud list page?

### ISSUE THREAD

**Issue by jishnu2292** [Gaspertrix/laravel-backpack-dropzone-field#4]
Dropzone can be used as image upload field, but how can we use it to view the images, ie, how can i add as column in backpack

**Comment by shineirvin** [comment]
Is this package abandoned ? :)

**Comment by Gaspertrix** [comment]
Sorry about late reply.
> 
> 
> Dropzone can be used as image upload field, but how can we use it to view the images, ie, how can i add as column in backpack
Package can be used for images and files too.
I don't think there is a good way to display a generic column to support that.

But you can implement your own [custom column](https://backpackforlaravel.com/docs/3.6/crud-columns#creating-a-custom-column-type)



> 
> 
> Is this package abandoned ? :)
Not really, even if it seems. I will be more active.
Feel free to open a new issue if you have any problem or a suggestion.
